### PR TITLE
Seed maps and heroes

### PR DESCRIPTION
**Pull request by cheshire137**
This adds Rails seeds so that we have Overwatch's maps and heroes loaded into the database for developing with. This is based on `implement-data-model` #5.

Here's the output of running `bin/rake db:seed`:

```
Creating support heroes: Mercy, Zenyatta, Ana, Lúcio, and Symmetra
Creating tank heroes: D.Va, Winston, Reinhardt, Orisa, Roadhog, and Zarya
Creating offense heroes: McCree, Pharah, Genji, Tracer, Sombra, Soldier: 76, and Reaper
Creating defense heroes: Hanzo, Widowmaker, Torbjörn, Bastion, Mei, and Junkrat
Creating assault maps: Hanamura, Temple of Anubis, and Volskaya Industries
Creating escort maps: Dorado, Route 66, and Watchpoint: Gibraltar
Creating hybrid maps: Eichenwalde, Hollywood, King's Row, and Numbani
Creating control maps: Ilios, Lijiang Tower, Nepal, and Oasis
Creating arcade maps: Ecopoint: Antarctica
Creating segments for map Hanamura: Attacking: First Point, Attacking: Second Point, Defending: First Point, and Defending: Second Point
Creating segments for map Temple of Anubis: Attacking: First Point, Attacking: Second Point, Defending: First Point, and Defending: Second Point
Creating segments for map Volskaya Industries: Attacking: First Point, Attacking: Second Point, Defending: First Point, and Defending: Second Point
Creating segments for map Ilios: Well, Ruins, and Lighthouse
Creating segments for map Lijiang Tower: Night Market, Control Center, and Garden
Creating segments for map Nepal: Village, Shrine, and Sanctum
Creating segments for map Oasis: City Center, Gardens, and University
Creating segments for map Hollywood: Attacking: Capture Point 1, Attacking: Payload 1, Attacking: Payload 2, Defending: Capture Point 1, Defending: Payload 1, and Defending: Payload 2
Creating segments for map Dorado: Attacking: Payload 1, Attacking: Payload 2, Attacking: Payload 3, Defending: Payload 1, Defending: Payload 2, and Defending: Payload 3
Creating segments for map King's Row: Attacking: Capture Point 1, Attacking: Payload 1, Attacking: Payload 2, Defending: Capture Point 1, Defending: Payload 1, and Defending: Payload 2
Creating segments for map Numbani: Attacking: Capture Point 1, Attacking: Payload 1, Attacking: Payload 2, Defending: Capture Point 1, Defending: Payload 1, and Defending: Payload 2
Creating segments for map Route 66: Attacking: Payload 1, Attacking: Payload 2, Attacking: Payload 3, Defending: Payload 1, Defending: Payload 2, and Defending: Payload 3
Creating segments for map Watchpoint: Gibraltar: Attacking: Payload 1, Attacking: Payload 2, Attacking: Payload 3, Defending: Payload 1, Defending: Payload 2, and Defending: Payload 3
Creating segments for map Eichenwalde: Attacking: Capture Point 1, Attacking: Payload 1, Attacking: Payload 2, Defending: Capture Point 1, Defending: Payload 1, and Defending: Payload 2
Creating segments for map Ecopoint: Antarctica: Attack
```

/cc @RobThePM for input on more map segments to add

### CODE REVIEW

**Comment by RobThePM** [comment]
sorry, i saw this late. my only super nit picky suggestion would be to add the colon (:) in soldier 76's name so that it's soldier: 76, since we do it for the map names. unless that somehow messes with the code.

**Comment by cheshire137** [comment]
Colon added! I also fleshed out the rest of the map segments.

**Comment by RobThePM** [comment]
I forgot to include Eichenwalde, thanks for remembering!

(my Google sheet was leveraged from Season 1 and 2, when Eichenwalde didn't exist)

**Comment by rewinfrey** [comment]
Awesome! 🎉

**Pull request merged**
