### PR TITLE
Add placeholder 'About' page

### PR DESCRIPTION
**Pull request by cheshire137**
For #31, this adds a mostly empty About page that's linked from a new footer area.

overwatchteamcomps

/cc @RobThePM for content ✨

### CODE REVIEW

**Comment by cheshire137** [comment]
You can comment here or in #31 with the content you'd like to see on this page, Rob. I'll work it into this branch, unless you want to edit some JSX!

**Comment by RobThePM** [comment]
thanks chesh, my ETA for completing this is either by 3/25 or 4/1

**Comment by cheshire137** [comment]
I landed this placeholder, Rob, but I saw you'd opened #92 so you can put any copy there and I'll get it into the app!

**Comment by RobThePM** [comment]
Thanks. Sorry - I was in a rush and I didn't review all of the open issues before creating a new one.

**Pull request merged**
