### PR TITLE
Only allow authentication via Battle.net

### LINKED ISSUE #14: Hook up user authentication
We have a `users` table and the [Devise gem](https://github.com/plataformatec/devise) for authentication. It would be cool if users could register and sign in. This would give us a `current_user` in controllers such that we could tie new Composition records to that User so the user can log in later and edit them.

We can start with basic user name and password authentication, and add OAuth authentication via Discord, etc. later.

We could present login + registration forms in two ways:

- Via React components in app/assets/javascripts/components/, using a single HTML page.
- Via separate pages as is the Devise default, leaving single-page stuff for the team composition form, specifying the heroes you main, etc.

### PR DESCRIPTION
**Pull request by cheshire137**
This branch does two things:

- Puts 'Sign in with Battle.net' / 'Signed in as'  in the top right corner, depending on whether the user has signed in or not.
- Removes the ability for a user to register an account using just an email address and password. This is a simplification I'm making for a few reasons:
    - I think it's reasonable to expect users of the app to have a Battle.net account, because I expect them to be Overwatch players.
    - This lets us have a battletag for each user instead of just for users who choose to sign in via Battle.net.
    - This saves us time styling several Devise views (create an account, sign in via email + password, password recovery).
    - This simplifies the interface we present to the user. No more paralysis of choice over how to authenticate with the app: you just click the single "sign in with Battle.net" link.
- This branch does _not_ remove the email address requirement from the initial signup flow. After authenticating with Battle.net the first time, the user is asked to provide an email address before they are fully signed up. If we want to drop this requirement in the future, I say we do it in a follow-up branch. I rather like having an email address for each user, though.
- This also fixes a bug where Rails' `current_user` would be nil after signing in if you were an existing user.

----

**Screenshot when logged in:**

overwatchteamcomps

This closes #14.

/cc @ihavenotea and @rewinfrey for code review

### CODE REVIEW

**Comment by RobThePM** [comment]
Everything seems fine to me.

When users provide an email address, do they have to go through the entire process of receiving an email in order to confirm that it's their email address?

Also, I want to approve this PR, but I'm on my phone and I don't see the approve button. Am I able to approve on the phone?

**Comment by cheshire137** [comment]
> do they have to go through the entire process of receiving an email in order to confirm that it's their email address?

They do not. We can enable such a feature via Devise, though it would involve some work to make sure our mailer is set up correctly so the app can send emails. I think it's fine to leave the email confirmation out for now. Looks like Devise has some built-in checks to make sure the email address they give us is at least somewhat valid, like they can't just tell us any old thing that doesn't look like an email address.

**Comment by cheshire137** [comment]
> Am I able to approve on the phone?

**Comment by RobThePM** [comment]
Okay. Well, I approve this PR. I think it's better that users don't have to confirm their email for this first version, but good to know what the options are. Thanks!

**Pull request merged**
